version: '3.5'
services:
  app:
    container_name: sports-blog
    restart: always
    build: .
    volumes:
      - ./uploads:/usr/src/app/uploads
    links:
      - mongo
  mongo:
    container_name: sports-mongo
    image: mongo
    restart: unless-stopped
    ports:
      - '27017:27017'
    volumes:
      - data-volume:/data/db

  nginx:
    container_name: sports-nginx
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev

    ports:
      - '80:80'
  
volumes:
  data-volume:
  node_modules:



    